great/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path

urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r'', include('photos.urls'), name='index'),
    path(r'login/', auth_views.LoginView.as_view(), name='login-view'),
    path(r'logout/', auth_views.LogoutView.as_view(), name='logout-view'),
    path(r'photologue/', include('photologue.urls'), name='photologue'),
]

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

photos/urls.py
from django.urls import path

from .views import \
    IndexView, UserUploadPhotoView,\
    PhotosToApprove, PhotoView, \
    PhotoLikeView, RejectPhotoView, \
    ApprovePhotoView

app_name = 'photos'
urlpatterns = [
    path(r'', IndexView.as_view(), name='index'),
    path(r'<slug>', PhotoView.as_view(), name='photo_detail'),
    path(r'photo/<photo_id>/like/', PhotoLikeView.as_view(), name='photo_like'),
    path(r'approve/', PhotosToApprove.as_view(), name='to_approve'),
    path(r'approve/<photo_id>/', ApprovePhotoView.as_view(), name="approve"),
    path(r'reject/<photo_id>', RejectPhotoView.as_view(), name="reject"),
    path(r'upload/', UserUploadPhotoView.as_view(), name='upload'),
]

photos/models.py
from django.contrib.auth import get_user_model
from django.db import models
# Create your models here.
from django.urls import reverse
from photologue.models import Photo

User = get_user_model()


class SitePhoto(Photo):
    approved = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    @property
    def likes(self):
        likes_for_this_pic = Like.objects.filter(picture_id=self.id)
        return likes_for_this_pic.count()

    def get_absolute_url(self):
        return reverse('photos:photo_detail', args=[self.slug])


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    picture = models.ForeignKey(SitePhoto, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

photos/forms.py
from django import forms

from photos.models import Like


class LikeForm(forms.ModelForm):

    class Meta:
        model = Like
        fields = '__all__'

photos/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, DeleteView, UpdateView
from photologue.views import PhotoListView, PhotoDetailView

from photos.mixins import PhotoApprovedOrNotMixin
from photos.models import SitePhoto, Like


class IndexView(PhotoApprovedOrNotMixin, PhotoListView):
    """
    This view brings my index and here I passed some other
    context like the counter of photos waiting in the queue
    """
    template_name = 'photos/gallery_index.html'
    paginate_by = 10
    context_object_name = 'photos'

    def get_queryset(self):
        if self.request.GET.get('order_by_like'):
            return sorted(
                self.photos_approved(),
                key=lambda photo: int(photo.likes),
                reverse=True
            )
        return self.photos_approved().order_by(
            'date_added'
        )

    def get_context_data(self, *args, **kwargs):
        context = super(IndexView, self).get_context_data()
        photos_to_approve = self.photos_declined().count()
        context['photos_to_approve'] = photos_to_approve
        return context


class PhotoView(PhotoApprovedOrNotMixin, PhotoDetailView):
    """
    Detail view, basicaly passing the Likes counter for
    this specific object
    """
    model = SitePhoto
    context_object_name = 'object'

    def get_context_data(self, *args, **kwargs):
        context = super(PhotoView, self).get_context_data()
        photos_to_approve = self.photos_declined().count()
        context['photos_to_approve'] = photos_to_approve
        context['likes'] = Like.objects.filter(picture_id=self.object.id)
        return context

    def get_queryset(self):
        return self.photos_approved()


class PhotosToApprove(LoginRequiredMixin, PhotoApprovedOrNotMixin, PhotoListView):
    """
    This view returns all the Photos not approved
    """
    template_name = 'photos/gallery_photos_to_approve.html'
    paginate_by = 10
    context_object_name = 'photos'

    def get_context_data(self, *args, **kwargs):
        context = super(PhotosToApprove, self).get_context_data()
        photos_to_approve = self.photos_declined().count()
        context['photos_to_approve'] = photos_to_approve
        return context

    def get_queryset(self):
        return self.photos_declined()


class PhotoLikeView(LoginRequiredMixin, CreateView):
    """
    Basically in this view, I made a custom validation
    to check whether the user already liked that specific
    picture, first I get all the likes he has in the DB
    if appears a like related to this Photo instance, it gets
    rejected and the counter does not continue. Just one like
    per user in each photo.
    """
    success_url = reverse_lazy('photos:index')
    model = Like
    fields = ['user', 'picture', ]
    queryset = Like.objects.all()

    def form_invalid(self, form):
        return redirect(reverse('photos:index'))

    def form_valid(self, form):
        picture_id = int(self.kwargs['photo_id'])
        pictures_that_user_liked = Like.objects.filter(user=form.instance.user)
        for like in pictures_that_user_liked:
            if like.picture.id == picture_id:
                return self.form_invalid(form)
        return super(PhotoLikeView, self).form_valid(form)

    def get_form_kwargs(self):
        kwargs = super(PhotoLikeView, self).get_form_kwargs()
        kwargs['data'] = {
            'user': self.request.user.id,
            'picture': self.kwargs['photo_id']
        }
        return kwargs


class UserUploadPhotoView(PhotoApprovedOrNotMixin, LoginRequiredMixin, CreateView):
    model = SitePhoto
    fields = ['title', 'image']
    success_url = reverse_lazy('photos:index')

    def get_context_data(self, *args, **kwargs):
        context = super(UserUploadPhotoView, self).get_context_data()
        photos_to_approve = self.photos_declined().count()
        context['photos_to_approve'] = photos_to_approve
        return context

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.slug = form.instance.title.replace(' ', '')
        return super(UserUploadPhotoView, self).form_valid(form)


class RejectPhotoView(PhotoApprovedOrNotMixin, DeleteView):
    model = SitePhoto
    pk_url_kwarg = 'photo_id'
    success_url = reverse_lazy('photos:to_approve')

    def get_queryset(self):
        return self.photos_declined()


class ApprovePhotoView(SuccessMessageMixin, PhotoApprovedOrNotMixin, UpdateView):
    model = SitePhoto
    fields = 'approved',
    pk_url_kwarg = 'photo_id'
    success_url = reverse_lazy('photos:to_approve')
    success_message = 'The photo is now in your feed :)'

    def get_queryset(self):
        return self.photos_declined()

photos/templates/photos/gallery_index.html
{% extends 'photologue/photo_list.html' %}
{% block title %}Joey&Sue{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        {% if object_list %}
            <ul class="float-sm-right">
                <li>
                    <a href="{% url 'photos:index' %}">Most Recent</a>
                </li>
                <li>
                    <a href="{% url 'photos:index' %}?order_by_like=true">Most Liked</a>
                </li>
            </ul>
            <div class="row d-flex justify-content-center">
                {% for photo in photos %}
                    <div class="card col-3">
                        <div class="card-img">
                            <a href="{% url 'photos:photo_detail' photo.slug %}">
                                <img
                                        src="{{ photo.get_thumbnail_url }}"
                                        alt="{{ photo.title }}"
                                        width="100%"
                                        height="200px"/>
                            </a>
                        </div>

                        <div class="card-body">

                            <div class="control-thumbnail">
                                <div class="title__like">
                                    <p>{{ photo.title }}</p>
                                    {% with photo.likes as like %}
                                        {% if like %}
                                            <p>{{ like }} Likes</p>
                                        {% endif %}
                                    {% endwith %}
                                </div>

                                <form method="post">
                                    {% csrf_token %}
                                    <button
                                            class="btn-lg btn-primary"
                                            formaction="{% url 'photos:photo_like' photo.id %}">
                                        <i class="fas fa-thumbs-up"></i>
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <div class="text-header">No photos were found.</div>
            {% include "photologue/includes/paginator.html" %} {% endif %} {% else %}

        <div class="form-group text-white text-header form-box">
            <h3>
                If you want to see our Wedding Album, email-us we gonna be happy to provide
                you an account
            </h3>
            <h5 class="text-capitalize text">sue@email.com</h5>
        </div>
    {% endif %}
{% endblock %}

photos/templates/photos/gallery_photos_to_approve.html
{% extends 'photologue/photo_list.html' %}

{% block title %}Joey&Sue{% endblock %}

{% block content %}

    {% if messages %}
        <div role="alert" class="alert alert-success">
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </div>
    {% endif %}

    {% if user.is_authenticated %}
        {% if object_list %}
            <div class="row col-lg-12">
                <h1 class="text-header text-white">All Photos of the Wedding</h1>
            </div>
            {% for photo in photos %}
                <div class="row m-4 text-white">
                    <div class="col-12 d-flex">
                        <img
                                src="{{ photo.get_display_url }}"
                                alt="{{ photo.title }}" />

                        <div class="d-flex flex-column justify-content-center m-3">
                            <h4>Sent by: {{ photo.user }}</h4>

                            <form action="{% url 'photos:approve' photo.id%}">
                                {% csrf_token %}
                                <button class="btn btn-success m-1">
                                    Approve
                                </button>
                            </form>

                            <form method="post" action="{% url 'photos:reject' photo.id%}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger m-1">
                                    Reject
                                </button>
                            </form>

                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <h1 class=" text-header text-white">No photos to approve.</h1>
            {% include "photologue/includes/paginator.html" %}
        {% endif %}
    {% endif %}
{% endblock %}

photos/templates/photos/sitephoto_confirm_delete.html
{% extends 'base.html' %} {% block title %}Joey&Sue - Upload{% endblock %}

{%block content %}
    <div class="form-group text-white form-box">
        <h3 class="text-header">
            Are you sure?! After that the photo is gone :(
        </h3>
            <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                <button class="btn btn-danger btn-block" type="submit">
                    Im Sure!
                </button>
            </form>
    </div>
{% endblock %}

photos/templates/photos/sitephoto_detail.html
{% extends 'photologue/photo_detail.html' %}
{% block title %} Detail {% endblock %}
{% block content %}
<div class="form-group text-white form-box">
    <div class="row d-flex m-5 justify-content-center">

        <div class="col-6 text-center">
            {% if object.caption %}
                <p>{{ object.caption | safe }}</p>
            {% endif %}

            <a href="{{ object.image.url }}">
                <img
                    src="{{ object.get_display_url }}"
                    class="img-fluid"
                    width="100%"
                    height="400px"
                    alt="{{ object.title }}"
                />
            </a>
        </div>

        <div class="col-md-6 col-sm-12 text-left text-md-center text-sm-center">
            <h1 class="page-header text-white">{{ object.title }}</h1>
            <p class="text-left">Likes:</p>

            <div class="overflow-auto d-flex" style="height: 50px">
                <ul>
                    {% for like in likes %}
                        <ul>{{ like.user }}</ul>
                    {% endfor %}
                </ul>
            </div>

            <p class="text-white">
                <small>"Published"{{ object.date_added }}</small>
            </p>

        </div>
    </div>
</div>
{% endblock %}

photos/templates/photos/sitephoto_form.html
{% extends 'base.html' %} {% block title %}Joey&Sue - Upload{% endblock %}
{% block content %}
<div class="form-group text-white form-box">
    <h3 class="text-header">Send me a picture from our Wedding!</h3>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary btn-block" type="submit">
            Send!
        </button>
    </form>
</div>
{% endblock %}

templates/base.html
{% load static %} <!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
        <meta name="description" content="{% block description %}{% endblock %}" />
        <meta name="keywords" content="{% block keywords %}{% endblock %}" />
        <meta name="viewport" content="{% block viewport %}width=device-width{% endblock %}"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <title>{% block title %}Sue&Joey{% endblock title %}</title>
        <link
          href="https://fonts.googleapis.com/css?family=Staatliches"
          rel="stylesheet"/>
        <link
          rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
          integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/"
          crossorigin="anonymous"/>
        <link href="{% static 'css/base.css' %}" rel="stylesheet" />
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
        <link href="{% static 'css/style.css' %}" rel="stylesheet" />

        {% block css %}
        {% endblock %}

    </head>
    <body>
        <header>
            <ul class="nav justify-content-center">

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'photos:index' %}">
                        <i class="fas fa-images"></i> Our Album!!
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'photos:upload' %}">
                        <i class="fas fa-plus-square"></i> Upload a Pic
                    </a>
                </li>

                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout-view' %}">
                            <i class="fas fa-sign-out-alt"></i> Logout
                        </a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login-view' %}">
                            <i class="fas fa-sign-in-alt"></i> Login
                        </a>
                    </li>
                {% endif %}

                {% if request.user.is_staff %}
                    <li class="nav-item float-sm-right">
                        <a class="nav-link" href="{% url 'photos:to_approve' %}">
                            <i class="fas fa-exclamation"></i>
                            {{ photos_to_approve }} Pics to Approve
                        </a>
                    </li>
                {% endif %}
            </ul>
    </header>

    <div class="subheader text-white text-header">
        <h3>
            Hey! Welcome!
            {% if user.is_authenticated %} {{ user.username }} {% endif %}
        </h3>
    </div>

    <div class="container-fluid">
        {% block content %} {% endblock content %}
    </div>

        {% block javascript %}

        {% endblock javascript %}
  </body>
</html>